<a href="https://colab.research.google.com/github/frdprd/examples/blob/master/Finviz_DividendList.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install finvizfinance

In [39]:
import pandas as pd
from finvizfinance.quote import finvizfinance
from finvizfinance.screener.overview import Overview
from finvizfinance.screener.financial import Financial
from finvizfinance.screener.valuation import Valuation

In [ ]:
foverview = Overview()
filter_1 = {'Country':'USA', 'Market Cap.': '+Mid (over $2bln)'} #'Index':'S&P 500', 
foverview.set_filter(filters_dict=filter_1)
df = foverview.screener_view()
df.count()

In [35]:
#keep 1000 largest cap
df=df.nlargest(1000, ['Market Cap'])
#drop rows for real estate
df = df[df.Sector != 'Real Estate']
#drop useless columns 
df=df.drop(columns=['Industry','Country','Market Cap','P/E','Price','Change','Volume'])

In [ ]:
#add yield column
#first download fundamentals with same filter
ffinancial = Financial()
filter_1 = {'Country':'USA', 'Market Cap.': '+Mid (over $2bln)'} #'Index':'S&P 500', 
ffinancial.set_filter(filters_dict=filter_1)
df2 = ffinancial.screener_view()
#Then, join
df2.count()

In [ ]:
#Then, join
df3 = pd.merge(df, df2, how='left', on=['Ticker'])
df3.count()

In [51]:
#keep 200 largest yields
df4=df3.nlargest(200, ['Dividend'])
#keep only useful columns
df4 = df4[['Ticker', 'Company', 'Sector','Dividend', 'ROA']]
df4.count()

Ticker      200
Company     200
Sector      200
Dividend    200
ROA         175
dtype: int64

In [68]:
#keep the top 4 ROA by sector
#sorting first
df4 = df4.sort_values(['Sector', 'ROA'], ascending=False)
df5=df4.groupby('Sector').head(4)
df5.head(5)

    Ticker                         Company      Sector  Dividend    ROA
551    NRG                NRG Energy, Inc.   Utilities    0.0320   0.12
664    UGI                 UGI Corporation   Utilities    0.0416  0.079
663    OGE                OGE Energy Corp.   Utilities    0.0460  0.073
388    CMS          CMS Energy Corporation   Utilities    0.0325  0.045
48     TXN  Texas Instruments Incorporated  Technology    0.0316  0.349

In [72]:
#keeping the top20 ROA
df5 = df5.sort_values(['ROA'], ascending=False)
df6=df5.head(20).sort_values(['Sector'], ascending=False).reset_index(drop=True)
df6

,Ticker,Company,Sector,Dividend,ROA
0,NRG,"NRG Energy, Inc.",Utilities,0.0320,0.12
1,TXN,Texas Instruments Incorporated,Technology,0.0316,0.349
2,CSCO,"Cisco Systems, Inc.",Technology,0.0342,0.125
3,HPQ,HP Inc.,Technology,0.0367,0.161
4,AVGO,Broadcom Inc.,Technology,0.0360,0.135
5,UPS,"United Parcel Service, Inc.",Industrials,0.0365,0.159
6,MSM,"MSC Industrial Direct Co., Inc.",Industrials,0.0389,0.131
7,PFE,Pfizer Inc.,Healthcare,0.0350,0.158
8,TROW,"T. Rowe Price Group, Inc.",Financial,0.0450,0.197
9,BX,Blackstone Inc.,Financial,0.0624,0.129
10,COP,ConocoPhillips,Energy,0.0351,0.174
11,PXD,Pioneer Natural Resources Company,Energy,0.0957,0.166
12,DVN,Devon Energy Corporation,Energy,0.0609,0.239
13,MMP,"Magellan Midstream Partners, L.P.",Energy,0.0792,0.125
14,PM,Philip Morris International Inc.,Consumer Defensive,0.0567,0.217
15,PKG,Packaging Corporation of America,Consumer Cyclical,0.0419,0.123
16,LYB,LyondellBasell Industries N.V.,Basic Materials,0.0577,0.145
17,HUN,Huntsman Corporation,Basic Materials,0.0311,0.139
18,SCCO,Southern Copper Corporation,Basic Materials,0.0620,0.163
19,CC,The Chemours Company,Basic Materials,0.0346,0.116